package com.example.userregistration.entity;

import com.example.userregistration.utils.DateUtil;

import java.io.Serializable;
import java.util.Date;

public class Customers implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.id
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.username
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.password
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.email
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.address
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.create_date
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.update_date
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    private Date update_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customers
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.id
     *
     * @return the value of customers.id
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.id
     *
     * @param id the value for customers.id
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.username
     *
     * @return the value of customers.username
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.username
     *
     * @param username the value for customers.username
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.password
     *
     * @return the value of customers.password
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.password
     *
     * @param password the value for customers.password
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.email
     *
     * @return the value of customers.email
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.email
     *
     * @param email the value for customers.email
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.address
     *
     * @return the value of customers.address
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.address
     *
     * @param address the value for customers.address
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.create_date
     *
     * @return the value of customers.create_date
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.create_date
     *
     * @param create_date the value for customers.create_date
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.update_date
     *
     * @return the value of customers.update_date
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public Date getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.update_date
     *
     * @param update_date the value for customers.update_date
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    public void setUpdate_date(Date update_date) {
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", email=").append(email);
        sb.append(", address=").append(address);
        sb.append(", create_date=").append(DateUtil.formatDate(create_date, "yyyy-MM-dd HH:mm:ss"));
        sb.append(", update_date=").append(DateUtil.formatDate(update_date, "yyyy-MM-dd HH:mm:ss"));
        sb.append("]");
        return sb.toString();
    }
}