package com.example.userregistration.dao;

import com.example.userregistration.entity.Customers;
import com.example.userregistration.entity.CustomersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Dec 17 14:53:30 CST 2021
     */
    long countByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Dec 17 14:53:31 CST 2021
     */
    int deleteByExample(CustomersExample example);

    int deleteCustomer(@Param("customers") Customers customers);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Dec 17 14:53:31 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Dec 17 14:53:31 CST 2021
     */
    int insert(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Dec 17 14:53:31 CST 2021
     */
    int insertSelective(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Dec 17 14:53:31 CST 2021
     */
    List<Customers> selectByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Dec 17 14:53:31 CST 2021
     */
    Customers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Dec 17 14:53:31 CST 2021
     */
    int updateByExampleSelective(@Param("record") Customers record, @Param("example") CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Dec 17 14:53:31 CST 2021
     */
    int updateByExample(@Param("record") Customers record, @Param("example") CustomersExample example);

    int updateCustomer(@Param("customers") Customers customers);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Dec 17 14:53:31 CST 2021
     */
    int updateByPrimaryKeySelective(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Dec 17 14:53:31 CST 2021
     */
    int updateByPrimaryKey(Customers record);
}