version: '2.2'
services:
  webapp:
    image: userregistration:latest
    container_name: userregistration
    ports:
      - "8080:8080"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/data"
    depends_on: 
      - redis
      - mysql
    networks:
      webapp:
        ipv4_address: 172.16.238.10

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./redis/redis.conf:/etc/redis/redis.conf"
    command: redis-server /etc/redis/redis.conf
    networks:
      webapp:
        ipv4_address: 172.16.238.11

  mysql:
    image: mysql:latest
    container_name: mysql
    platform: linux/x86_64
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
       - "3306:3306"
    volumes:
       - "./db:/var/lib/mysql"
       - "./conf/my.cnf:/etc/my.cnf"
       - "./init:/docker-entrypoint-initdb.d/"
    networks:
      webapp:
        ipv4_address: 172.16.238.12

networks:
  webapp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

